server:
  port: 9091

---
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    activate:
      secret: a-string-secret-at-least-256-bits-long
      on-profile: qa
  datasource:
    url: jdbc:mysql://172.20.96.5:3306/MVPCLOUDSEALS
    username: gopi
    password: Gmail@123
  mail:
    host: smtp.office365.com
    port: 587
    username: admin.mvp@cloudseals.com
    password: vkzzccvtzdndxlwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none






