springdoc:
  api-docs:
    path: /v3/api-docs       # where Springdoc exposes your spec
  swagger-ui:
    path: /swagger-ui   # or /swagger-ui/index.html
    url: /v3/api-docs
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    activate:
      secret: a-string-secret-at-least-256-bits-long
      on-profile: qa
  datasource:
    url: jdbc:mysql://172.20.96.5:3306/MVPCLOUDSEALS
    username: gopi
    password: Gmail@123
  mail:
    host: smtp.office365.com
    port: 587
    username: admin.mvp@cloudseals.com
    password: vkzzccvtzdndxlwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none






